/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiLeadershipRouteImport } from './routes/ai-leadership'
import { Route as IndexRouteImport } from './routes/index'

const AiLeadershipRoute = AiLeadershipRouteImport.update({
  id: '/ai-leadership',
  path: '/ai-leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-leadership': typeof AiLeadershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-leadership': typeof AiLeadershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-leadership': typeof AiLeadershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-leadership'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-leadership'
  id: '__root__' | '/' | '/ai-leadership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLeadershipRoute: typeof AiLeadershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai-leadership': {
      id: '/ai-leadership'
      path: '/ai-leadership'
      fullPath: '/ai-leadership'
      preLoaderRoute: typeof AiLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLeadershipRoute: AiLeadershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
